// RQ-ABT-001 / D-62 / D-64
// Widget tests for the About dialog accessible from the HomeScreen AppBar.
// Verifies the info button exists and that tapping it opens the About dialog
// with the expected content (app name, version, author, licence, attribution).
// Model: Claude Opus 4.6

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:package_info_plus/package_info_plus.dart';

import 'package:flutins/core/constants/app_constants.dart';
import 'package:flutins/data/providers/package_info_provider.dart';
import 'package:flutins/domain/entities/tag.dart';
import 'package:flutins/domain/value_objects/sort_option.dart';
import 'package:flutins/presentation/home/home_screen.dart';
import 'package:flutins/presentation/home/item_list_provider.dart';
import 'package:flutins/presentation/home/tag_list_provider.dart';

// ---------------------------------------------------------------------------
// Fakes
// ---------------------------------------------------------------------------

/// Returns an empty item list without touching the database or any stream
/// -- keeps these About-dialog tests free of Drift stream timers.
class _FakeItemListNotifier extends ItemListNotifier {
  @override
  Stream<ItemListState> build() => Stream.value(
        ItemListState(
          items: const [],
          sort: SortOption.defaultSort,
        ),
      );
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const _testVersion = '1.2.3';
const _testBuildNumber = '42';
const _expectedVersion = '$_testVersion+$_testBuildNumber';
const _aboutAuthor = 'spashx';
const _aboutLicence = 'GPL-3.0';
const _attributionFragment = 'Entirely generated by AI';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

Widget _buildTestApp() {
  return ProviderScope(
    overrides: [
      itemListNotifierProvider
          .overrideWith(_FakeItemListNotifier.new),
      tagListProvider
          .overrideWith((ref) => Stream.value(const <Tag>[])),
      packageInfoProvider.overrideWith(
        (_) async => PackageInfo(
          appName: AppConstants.appName,
          packageName: AppConstants.packageId,
          version: _testVersion,
          buildNumber: _testBuildNumber,
        ),
      ),
    ],
    child: const MaterialApp(
      home: HomeScreen(),
    ),
  );
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

void main() {
  group('About dialog -- D-62 / D-64 / RQ-ABT-001', () {
    // -----------------------------------------------------------------------
    // Info button presence
    // -----------------------------------------------------------------------

    testWidgets(
      'Given the home screen is displayed, '
      'When the default AppBar is visible, '
      'Then an info button is present',
      (tester) async {
        await tester.pumpWidget(_buildTestApp());
        await tester.pumpAndSettle();

        expect(
          find.byIcon(Icons.info_outline),
          findsOneWidget,
        );
      },
    );

    // -----------------------------------------------------------------------
    // About dialog opens
    // -----------------------------------------------------------------------

    testWidgets(
      'Given the home screen is displayed, '
      'When the user taps the info button, '
      'Then the About dialog is shown with app name and version',
      (tester) async {
        await tester.pumpWidget(_buildTestApp());
        await tester.pumpAndSettle();

        await tester.tap(find.byIcon(Icons.info_outline));
        await tester.pumpAndSettle();

        // App name appears in the dialog
        expect(find.text(AppConstants.appName), findsWidgets);

        // Version string
        expect(find.text(_expectedVersion), findsOneWidget);
      },
    );

    // -----------------------------------------------------------------------
    // Licence and author
    // -----------------------------------------------------------------------

    testWidgets(
      'Given the About dialog is open, '
      'When the user reads the legalese, '
      'Then the licence and author are displayed',
      (tester) async {
        await tester.pumpWidget(_buildTestApp());
        await tester.pumpAndSettle();

        await tester.tap(find.byIcon(Icons.info_outline));
        await tester.pumpAndSettle();

        expect(
          find.textContaining(_aboutLicence),
          findsOneWidget,
        );
        expect(
          find.textContaining(_aboutAuthor),
          findsOneWidget,
        );
      },
    );

    // -----------------------------------------------------------------------
    // AI attribution
    // -----------------------------------------------------------------------

    testWidgets(
      'Given the About dialog is open, '
      'When the user reads the dialog content, '
      'Then the AI-generation attribution is displayed',
      (tester) async {
        await tester.pumpWidget(_buildTestApp());
        await tester.pumpAndSettle();

        await tester.tap(find.byIcon(Icons.info_outline));
        await tester.pumpAndSettle();

        expect(
          find.textContaining(_attributionFragment),
          findsOneWidget,
        );
      },
    );

    // -----------------------------------------------------------------------
    // VIEW LICENSES button
    // -----------------------------------------------------------------------

    testWidgets(
      'Given the About dialog is open, '
      'When the user inspects available actions, '
      'Then a VIEW LICENSES button is present',
      (tester) async {
        await tester.pumpWidget(_buildTestApp());
        await tester.pumpAndSettle();

        await tester.tap(find.byIcon(Icons.info_outline));
        await tester.pumpAndSettle();

        expect(
          find.text('View licenses', skipOffstage: false),
          findsOneWidget,
        );
      },
    );
  });
}
